name: Runner System Report

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Optional: Every 6 hours – remove if not needed

jobs:
  report:
    runs-on: ubuntu-latest  # Change to windows-latest or macos-latest for different runners

    steps:
      - name: Collect System Info
        id: info
        run: |
          # Basic info
          echo "runner_os=${{ runner.os }}" >> $GITHUB_ENV
          echo "runner_name=${{ runner.name }}" >> $GITHUB_ENV
          echo "java_version=$(java -version 2>&1 | head -1 | cut -d'"' -f2)" >> $GITHUB_ENV
          
          # CPU cores
          echo "cpu_cores=$(nproc)" >> $GITHUB_ENV
          
          # Total RAM in GB
          echo "ram_gb=$(free -m | awk '/Mem:/ {print $2}')" >> $GITHUB_ENV
          ram_display=$(awk "BEGIN {printf \"%.1f\", ${{ env.ram_gb }} / 1024}")GB
          echo "ram_display=$ram_display" >> $GITHUB_ENV
          
          # Disk space in GB (root filesystem)
          disk_gb=$(df -h / | awk 'NR==2 {print $2}')
          echo "disk_gb=$disk_gb" >> $GITHUB_ENV
          
          # Public IP (using external service)
          public_ip=$(curl -s https://api.ipify.org || echo "Unknown")
          echo "public_ip=$public_ip" >> $GITHUB_ENV
          
          # Timestamp
          echo "timestamp=$(date +'%H:%M:%S')" >> $GITHUB_ENV

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.https://discord.com/api/webhooks/1456376982668443913/CirBvvRILmHlVYBCLetrBTSSuKW1mvReGngb8H4Vw5rrZ7KzmT1E0yto9ImkTFnS7Hbk }}  # Add your webhook URL as a repository secret!
        run: |
          curl -H "Content-Type: application/json" -d '{
            "username": "GitHub Runner Monitor",
            "embeds": [{
              "title": "Runner System Report - ${{ runner.os }}",
              "color": 3447003,
              "fields": [
                {"name": "Runner Name", "value": "`${{ runner.name }}`", "inline": true},
                {"name": "OS", "value": "`${{ runner.os }}`", "inline": true},
                {"name": "CPU Cores", "value": "`${{ env.cpu_cores }}`", "inline": true},
                {"name": "RAM", "value": "`${{ env.ram_display }}`", "inline": true},
                {"name": "Disk", "value": "`${{ env.disk_gb }}`", "inline": true},
                {"name": "Public IP", "value": "`${{ env.public_ip }}`", "inline": true},
                {"name": "Java Version", "value": "`${{ env.java_version }}`", "inline": true},
                {"name": "Time", "value": "`${{ env.timestamp }}`", "inline": true}
              ],
              "footer": {"text": "Generated by GitHub Actions"},
              "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
            }]
          }' "$DISCORD_WEBHOOK"
